version: "2.1"
services:
    rsnapshot:
        build: .
        container_name: rsnapshot
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London
        volumes:
            - ./config:/config
            - ./snapshots:/snapshots
        restart: unless-stopped
