#!/usr/bin/with-contenv bash

PERIOD=$1
NOW=$(date '+%d/%m/%Y %H:%M:%S');
RSNAPSHOT_FILE="/config/rsnapshot.conf"
SSH_KNOWNHOSTS="/root/.ssh/known_hosts"

echo "Running rsnapshot $PERIOD - $NOW"

if ! rsnapshot configtest; then
    echo "rsnapshot config is invalid"
    exit 1
fi

echo "Adding known hosts"
REMOTE_SSH=$(egrep -o "([0-9]{1,3}\.){3}[0-9]{1,3}" $RSNAPSHOT_FILE | sort | uniq)
[[ -f $SSH_KNOWNHOSTS ]] && rm $SSH_KNOWNHOSTS
touch $SSH_KNOWNHOSTS
while IFS= read -r line; do
    if [[ ! -z "$line" ]]; then
        echo "Adding $line to known hosts"
        ssh-keyscan -H $line >> $SSH_KNOWNHOSTS
    fi
done <<< "$REMOTE_SSH"
chmod 600 $SSH_KNOWNHOSTS

if ! rsnapshot $PERIOD; then
    echo "Backup failed at $NOW" >> /config/log/error-${PERIOD}.txt
    exit 1
fi

echo "Getting backup report"
echo "Backup complete at $NOW" > /config/log/report-${PERIOD}.txt
rsnapshot du >> /config/log/report-${PERIOD}.txt
echo "Backup complete"
