#!/usr/bin/with-contenv bash

mkdir -p /config/{log,key,crontabs}

if [[ ! -f /root/.ssh/id_rsa ]]; then
    mkdir -p /root/.ssh
    ssh-keygen -f /root/.ssh/id_rsa -q -N ""
    cp /root/.ssh/id_rsa.pub /config/key/
fi

[[ ! -f /config/rsnapshot.conf ]] && cp /defaults/rsnapshot.conf /config/rsnapshot.conf
rm -rf /etc/rsnapshot.conf
ln -s /config/rsnapshot.conf /etc/rsnapshot.conf

[[ ! -f /config/crontabs/root ]] && cp /defaults/crontabs /config/crontabs/root
rm /etc/crontabs/*
cp /config/crontabs/* /etc/crontabs/

chown -R abc:abc /config
chmod -R g+w /config
chmod -R 644 /etc/logrotate.d
chmod 700 /root/.ssh
chmod +x /scripts/rsnapshot
