#!/usr/bin/with-contenv bash

mkdir -p /config/{log,crontabs}

if [[ ! -d /config/key ]]; then
    mkdir -p /config/key
    ssh-keygen -f /config/key/id_rsa -q -N ""
fi

rm -rf /root/.ssh
mkdir -p /root/.ssh
cp -r /config/key/* /root/.ssh/
chmod -R 600 /root/.ssh

[[ ! -f /config/rsnapshot.conf ]] && cp /defaults/rsnapshot.conf /config/rsnapshot.conf
rm -rf /etc/rsnapshot.conf
ln -s /config/rsnapshot.conf /etc/rsnapshot.conf

[[ ! -f /config/crontabs/root ]] && cp /defaults/crontabs /config/crontabs/root
rm /etc/crontabs/*
cp -r /config/crontabs/* /etc/crontabs/

chown -R abc:abc /config
chmod -R g+w /config
chmod -R 644 /etc/logrotate.d
chmod +x /scripts/rsnapshot
chmod -R 766 /config/rsnapshot.conf

mkdir -p /snapshots
chown abc:abc /snapshots
